### ISSUE TITLE
performance problem reported

### ISSUE THREAD

**Issue by denfromufa** [ericremoreynolds/excelpython#41]
PyXLL and ExcelPython Performance Comparison:
http://pyxll.com/blog/performance-comparison/

**Comment by ericremoreynolds** [comment]
Thanks Denis,

I was aware of this article by the authors of PyXLL. I do not agree that ExcelPython has a performance 'problem' however.

The original version of ExcelPython (v1) was based on an in-process approach like PyXLL. This comes with a series of limitations, for example it's difficult to create an isolated Python environment for each workbook and a lot of people were experiencing DLL loading problems, which can happen because of slight differences in the PC's configuration or Python distributions or paths which have been tampered with.

One of the objectives of ExcelPython v2 was that as long as you can run "python.exe" from the command line on a PC, and that PC has PyWin32 installed, then ExcelPython should work too. To achieve this reliability was preferred over performance, which is a common trade-off in any software system.

ExcelPython v2 runs Python out-of-process, and as a result is bound to have worse performance than an in-process approach. However whether this is a 'problem' depends on how you're using it. The PyXLL article highlights a use case involving a very large number of small function calls, and in this case ExcelPython is not the right tool. But for many other use cases it's just fine. I myself use it professionally for various different applications and have never found performance to be serious issue.

Nonetheless, when I finally get around to v2.1, hopefully I will be able to address some of the points mentioned in the article! (as well as pandas dataframes and other things you have asked for in the past :smile: )

Best regards,

Eric.
