### ISSUE TITLE
Does ExcelPython work with Excel 2003?

### ISSUE THREAD

**Issue by excel4** [ericremoreynolds/excelpython#45]
The quickstart page says ExcelPython works with Excel versions >=2003. However I could not find a .xla file in any versions. Excel 2003 will not open .xlam files. I tried converting the .xlam file from 2.08 to .xla in Excel 2013 and then installing it in Excel 2003. Although Excel 2003 added the Add-in to the available add-ins, there is no menu item for Xlpython and I do not see any way to import the UDF.

Please advise,
Thanks!

**Comment by ericremoreynolds** [comment]
Hello excel4,

I think when I wrote that Excel >= 2003 is supported, I mistakenly assumed that `.xlam` were supported from 2003 onwards - as you correctly point out Excel 2003 doesn't open `.xlam` files. So sorry about that mistake.

Regarding how to make it work under Excel 2003, it is probably true that simple conversion of the `.xlam` to `.xla` is not sufficient, since the menus are in an XML format which may not be supported by Excel 2003. You should still be able to run the macros corresponding to the menu buttons from VBA, though I have not looked at how to make them readily available in 2003 as a menu or similar. Also please note that though the developer add-in does not work out of the box in 2003, I believe that ExcelPython-enabled workbooks developed with a later version of Excel will still be usable in Excel 2003, so in that sense it is supported.

You can understand that 2003 is now a very old version of Excel so it is not really worth the effort of supporting it, given the restricted user base (though I apologize for the misleading statement on the quick start page). However if you figure out how to do it any pull requests will be very welcome!

Kind regards,

Eric
