### ISSUE TITLE
Python NaN returns as 2.69e+308

### ISSUE THREAD

**Issue by skatastic** [ericremoreynolds/excelpython#55]
I noticed that if my python UDF had a float with NaN values that they returned to the Excel sheet as 2.69E+308.  I looked into it further and found that in the function after the line

MyFuncName = py.var(MyFuncName, True)

when I look in the Locals window at MyFuncName it is a variant and the values that become 2.69e+308 show up as 1.#QNAN

The simplest way I can think of to work around this is to convert NaNs to empty strings in python but maybe there's a way to "intercept" the NaN values that I'm not aware of in between python and VBA so they return something more sensible.

**Comment by ericremoreynolds** [comment]
Hi skatastic,

Just as with a few other issue posted over time, this kind of thing is due to how PyWin32 converts Python types and how Excel displays those values (I believe in this case the second aspect is more relevant, since like you point even outside the Python call, Excel is aware that the value is a NaN but chooses to display it as 2.69E+308).

I am not aware of any more appropriate work-around than the one you mentioned. Unfortunately PyWin32 and Excel both have some funny ways of treating some values and for now we just have to live with it... unless of course you'd like to develop the ExcelPython code and make a pull request :smile:.

Best regards,

Eric
