### ISSUE TITLE
Excel python future

### ISSUE THREAD

**Issue by AntonioSuriano** [ericremoreynolds/excelpython#61]
Hi Eric, 

I am going to develop an Excel app using Anaconda Python and I am choosing a library.

I don't know if to use xlwings (that has some issues but is in active development) or ExcelPython.
I'd like to know if Excel Python is going to be mantained in the future.

In particular:
1) I need both UDFs and macros, but expecially UDFs.
2) I will use Pandas' objects.

For 1 Excel Python is better.
For 2 I know xlwings is good.

**Comment by AntonioSuriano** [comment]
By the way what is the best way of using xlwings and excelpython together?

solution a:
use xlwings bas  module/DLL and manually copy vba generated code for wrappers from xlwings

solution b:
use ExcelPython module/DLL and import xlwings in .py file to use in the @xlsub routines (for example to paste pandas objects)?

**Comment by ericremoreynolds** [comment]
Hello Antonio,

As you correctly point out ExcelPython's main advantage compared with xlwings is indeed the UDF functionality.

@fzumstein and I have talking about integrating ExcelPython with xlwings more closely. In fact it's likely that in future we will move towards incorporating ExcelPython's functionality into xlwings and slowly deprecating ExcelPython, but I cannot give you a time frame for this. However, migrating will always be straightforward, so I don't this project has a big impact on the choice you're making right now.

It's true I haven't done much development work ExcelPython recently, however the present release is pretty stable.

With regards to xlwings compatibility - check out the comment in [this release](https://github.com/ericremoreynolds/excelpython/releases/tag/v2.0.4). That argument in the decorator is necessary so that xlwings knows which workbook to operate on.

Let me know how you get on!

Kind regards,

Eric

**Comment by AntonioSuriano** [comment]
Well, I tried the same subroutine imported with xlwings and xlpython.

excelwings: much faster
xlpython: no zombie python processes (when you reopen the file it connects to the old kernel with all the cache values before calculated).

I've not yet made a choice.

**Comment by fzumstein** [comment]
Hi Antonio, can you post the code that leaves you with Zombie processes on xlwings? We should get this under control hopefully soon, but in the meantime, things should actually work if you don't use global workbook objects (as a workaround).

**Comment by AntonioSuriano** [comment]
When I close Excel all pythonw die, but if I close the worksheet and reopen it connects to another pythonw.

You already answered me to this question a week ago... https://zoomeranalytics.uservoice.com/forums/269851-xlwings/suggestions/10172367-connect-to-existing-kernel

**Comment by fzumstein** [comment]
I see, I guess I understand your issue now. I don't think that your desired behaviour is possible without the introduction of an add-in, which is a bit further down the road.

**Comment by AntonioSuriano** [comment]
Well probably the best fit is to write micro-functions in VBA and large data processing in python.

**Comment by AntonioSuriano** [comment]
Hi, 

I realized that calling C/C++ functions from Excel or VBA is easier than I expected. 

(Public declare function lib _
"mydll.dll" .......)

If I were to embed a python session into a c++ class and compile my functions into a dll and call from vba through the "public declare", would my UDFs be in-process?

**Comment by ericremoreynolds** [comment]
Yes.

Or you could just use ExcelPython v1.

But beware in-process opens the door to a whole series of headaches.

**Comment by AntonioSuriano** [comment]
Yeah, wchar e char conversions...

and xlwings  make the Excel crash badly when called in-process.
