### ISSUE TITLE
ImportError: No module named 'numpy'

### ISSUE THREAD

**Issue by florin-onder** [ericremoreynolds/excelpython#67]
Hy there

I have an issue with the excelpython add in for excel. When I follow the tutorial on 
https://github.com/ericremoreynolds/excelpython/blob/master/docs/tutorials/Addin03.md
and type the exact same things in my python code, I get as a result, when I try to run the new function in excel the error: "ImportError: No module named 'numpy'". 
Do you have a fix for that issue?
In python, numpy works fine, but apparently not in the add in. 
Thanks a lot for your help.

**Comment by ericremoreynolds** [comment]
Hello Florin,

It is strange that you are getting this error, since in theory the Python process launched by the add-in is exactly the same as one launched externally. Perhaps you should check the `xlpython.cfg` file to make sure it's launching the same Python installation if you have more than one.

In any case ExcelPython is now a defunct project having been merged into xlwings, perhaps you can try migrating, it should be fairly painless.

Regards,

Eric
